name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # تغییر به نسخه قدیمی‌تر

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # تغییر به نسخه 3.9

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip3 install --upgrade pip
        pip3 install buildozer
        pip3 install Cython

    - name: Build APK with Buildozer
      run: |
        buildozer android debug deploy

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Yadaver-APK
        path: bin/*.apk
